export const PRO_RISE = {
  login: "auth/login",
  verifyEmail: "auth/verifyEmail",
  register: "user",
  addFavTrader: "user/addFavTrader",
  unFavoriteTrader: "user/unFavoriteTrader",
  isTraderFollowedByUser: "user/isTraderFollowedByUser",
  unfollowTrader: "user/unfollowTrader",
  subscribeToPackage: "user/subscribeToPackage",
  exchangeConection: "exchange",
  currentlyConnected: "exchange/currentlyConnected",
  copyTrade: "exchange/copyTrade",
  followTrader: "user/followTrader",
  getOpenPositions: "exchange/getOpenPositions",
  closePosition: "exchange/closePosition",
  getLeaderboardsData: "leaderboards/getLeaderboardsData",
  getTraderPositions: "leaderboards/getTraderPositions",
  getPlans: "plan/getPlans",
};
