export const PRO_RISE = {
  login: "auth/login",
  verifyEmail: "auth/verifyEmail",
  register: "user",
  addFavTrader: "user/addFavTrader",
  updateUserInfo: "user/update",
  changePassword: "user/changePassword",
  unFavoriteTrader: "user/unFavoriteTrader",
  getWalletBalance: "user/getWalletBalance",
  isTraderFollowedByUser: "user/isTraderFollowedByUser",
  unfollowTrader: "user/unfollowTrader",
  subscribeToPackage: "user/subscribeToPackage",
  getClosedTrades: "user/getClosedTrades",
  exchangeConection: "exchange",
  currentlyConnected: "exchange/currentlyConnected",
  getCapitalPercent: "exchange/defaultCapitalPercent",
  copyTrade: "exchange/copyTrade",
  followTrader: "user/followTrader",
  getOpenPositions: "exchange/getOpenPositions",
  getLeaderboardsData: "leaderboards/getLeaderboardsData",
  getTraderPositions: "leaderboards/getTraderPositions",
  getPlans: "plan/getPlans",
};
